name: Run Playwright Test

on:
  push:
    paths:
      - "scripts/**"    # Triggers on any change inside scripts folder or its subfolders
  # Or simply omit 'paths' to run on all pushes

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Playwright
        run: |
          npm install -D playwright
          npx playwright install

      - name: Run Playwright tests
        run: |
          npx playwright test scripts/
