name: Run Playwright Test

on:
  push:
    paths:
      - "scripts/**"  # Triggers on any change inside scripts folder or its subfolders

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -D @playwright/test
          npx playwright install

      - name: Run Playwright tests
        run: |
          npx playwright test scripts/
