name: Run Playwright Test

on:
  push:
    paths:
      - "scripts/test.spec.js"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Playwright
        run: |
          npm install -D playwright
          npx playwright install

      - name: Run Playwright test
        run: |
          node scripts/test.spec.js
